### ISSUE TITLE
Forum Helpers List: Changes

### ISSUE THREAD

**Issue by derter-menter** [theforumhelpers/theforumhelpers.github.io#305] opened 2022-01-13 16:30 UTC
**Describe the changes needed**
Some users need to be added to the page. This includes @rayli1123, @god286, @TheGlassPenguin, @prime689, @b1048546, @exphire, @helloworldbyeworld and @mrcreatorlugi

@chiryoce and @maximouse should be moved to the manager section

**Comment by derter-menter** [comment] 2022-01-13 16:31
Feel free to assign this to me

**Comment by Chiroyce1** [comment] 2022-01-15 07:49
I'll make a Python Script to make it easier, so we don't have to manually add the names to the JSON files.

**Comment by leahcimto** [comment] 2022-01-15 16:29
Duplicate of #302

**Closed** 2022-01-15 16:31 UTC
Labels: status: duplicate, type: Forum Helpers List
