### ISSUE TITLE
Bug: 404 page doesn't work sometimes

### ISSUE THREAD

**Issue by Accio1** [theforumhelpers/theforumhelpers.github.io#141] opened 2021-04-17 21:32 UTC
**Describe the bug**
If a URL is opened that should direct to the 404 page, it only displays properly sometimes.

If an invalid URL does not end in a slash, the page works fine, but if it ends in a slash the page doesn't display properly.

**To Reproduce**
Visit https://theforumhelpers.github.io/a - Observe that the 404 page works correctly
Now visit https://theforumhelpers.github.io/a/ Observe that the 404 page is broken

**Expected behavior**
The 404 page should appear correctly despite what URL is typed.

**Browser Information**
As far as I know, this is not browser specific.

**Additional context**
Reported by gosoccerboy5 here: https://scratch.mit.edu/studios/3688309/comments/#comments-141881066

**Comment by FunctionalMetatable** [comment] 2021-04-17 22:09
Related to #131.

**Comment by gosoccerboy5** [comment] 2021-04-19 14:19
I'm getting this bug on my own github page too.
I think the problem is that when you include the slash, it thinks it's a directory, and then trying to load a css or js file as **index.css** makes it think it's **theforumhelpers.github.io/randomword/index.css** instead of **theforumhelpers.github.io/index.css**, for example. 
I think this could be fixed by including the full link to **theforumhelpers.github.io/resources/stylesheet.css** instead of just **resources/stylesheet.css** because of the browser's assumption you're looking for something included in that directory.

Sorry if that was really confusing btw

**Comment by gosoccerboy5** [comment] 2021-04-19 14:22
Yep. I just made a fix to my own page for this bug, and all you have to do is probably replace **resources/stylesheet.css** with **//.../resources/stylesheet.css** or just **//theforumhelpers.github.io/resources/stylesheet.css** to make it clear to the browser what file you want loaded.

**Comment by Accio1** [comment] 2021-04-19 17:29
> Yep. I just made a fix to my own page for this bug, and all you have to do is probably replace **resources/stylesheet.css** with **//theforumhelpers.github.io/resources/stylesheet.css** to make it clear to the browser what file you want loaded.

This wouldn't work for anyone who would be developing this locally though. The / would direct to the base of their file system (file:///C:/ on windows) and the link would not work.

**Comment by jeffalo** [comment] 2021-04-20 06:49
use relative paths like ./ and stuff

**Comment by FunctionalMetatable** [comment] 2021-04-21 06:21
I think this whole site should move to jekyll or nuxt/vue. all the problems with this would go away as it would use "localhost" instead of C:\.

**Comment by gosoccerboy5** [comment] 2021-05-04 14:11
> I think this whole site should move to jekyll or nuxt/vue. all the problems with this would go away as it would use "localhost" instead of C:.

You love jekyll, huh

> > Yep. I just made a fix to my own page for this bug, and all you have to do is probably replace **resources/stylesheet.css** with **/resources/stylesheet.css** to make it clear to the browser what file you want loaded.
> 
> This wouldn't work for anyone who would be developing this locally though. The / would direct to the base of their file system (file:///C:/ on windows) and the link would not work.

Er, you may disagree with this, but I think I'd rather have it at least work for the users, than have it work for no one..

**Comment by gosoccerboy5** [comment] 2021-05-04 14:30
Also, the homepage link on the 404 page is broken too. So users could get confused and lost.

**Closed** 2021-05-05 11:40 UTC
Labels: priority: med, type: bug
