### ISSUE TITLE
Feature Request: [Dark Mode] Change The Search Bar Background Color

### ISSUE THREAD

**Issue by Shluffy** [theforumhelpers/theforumhelpers.github.io#216] opened 2021-06-08 18:12 UTC
https://user-images.githubusercontent.com/81823039/121236318-d07b6f80-c863-11eb-8806-a51cd5f5549b.mp4

This is what is happening.
A mockup of a possible change:

![image](https://user-images.githubusercontent.com/81823039/121237661-4d5b1900-c865-11eb-8f34-06f21e300c1e.png)

This simply changes `--searchBar:` under the dark mode part to `#222b2e` rather then `#1f1f1f` - pretty much black. 
@Accio1 if we are changing it (and to this color, or a slightly darker one) could I be assigned?

Edit: 
A screen recording of this in action:

https://user-images.githubusercontent.com/81823039/121240749-ad06f380-c868-11eb-858f-18b2744eef64.mp4

**Comment by Shluffy** [comment] 2021-06-08 18:27
A mockup of a possible change:

![image](https://user-images.githubusercontent.com/81823039/121237661-4d5b1900-c865-11eb-8f34-06f21e300c1e.png)

This simply changes `--searchBar:` under the dark mode part to `#222b2e` rather then `#1f1f1f` - pretty much black. 
@Accio1 if we are changing it (and to this color, or a slightly darker one) could I be assigned?

**Comment by Accio1** [comment] 2021-06-08 19:02
This is by design

**Comment by Shluffy** [comment] 2021-06-08 19:20
> This is by design

Maybe still change it? a black/dark grey works better then same as the background

**Comment by Shluffy** [comment] 2021-06-09 21:59
@Accio1 are we going to be doing this? if so can i be assigned? if not it would probably be needs discussion

**Comment by Shluffy** [comment] 2021-06-13 18:19
@Accio1 can i be assigned? this is just priority low and mini, but not needs discussion

**Comment by Accio1** [comment] 2021-06-13 18:21
If you can do it by using CSS Variables that are already declared, go ahead. However, please don't add a new one just for this button.

**Comment by Shluffy** [comment] 2021-06-13 18:45
> If you can do it by using CSS Variables that are already declared, go ahead. However, please don't add a new one just for this button.

it just changes one of the set things for each theme

**Comment by Accio1** [comment] 2021-06-13 19:55
Resolved in #238

**Closed** 2021-06-13 19:55 UTC
Labels: priority: low, type: mini, type: styling
