### ISSUE TITLE
Feature Request: Embed some of the studio projects.

### ISSUE THREAD

**Issue by DawnRooney27** [theforumhelpers/theforumhelpers.github.io#169] opened 2021-05-11 20:50 UTC
**Is your feature request related to a problem?**
No. I just would like to see this happen.

**Describe alternatives you've considered**
None yet.

**Additional context**
Nothing Yet.

**Comment by Accio1** [comment] 2021-05-11 20:53
Duplicate of #149

**Closed as completed** 2021-05-11 20:53 UTC
Labels: status: duplicate
